### ISSUE TITLE
Cannot build the project

### ISSUE THREAD

**Issue by almgwary** [archfirst/angular-material-template#1]
events.js:141

```
   throw er; // Unhandled 'error' event
      ^
Error: JSHint failed for: src\core\core.router.js, src\components\approot\approot.directive.js, src\components\home\home.directive.js, src\components\quickstart\quickstart.directive.js, src\components\Services\services.js, src\components\Services\uiService.js, src\components\Services\userservices.js, src\components\toolbar\toolbar.directive.js

```

**Comment by zygimantus** [comment]
You forgot to use `npm install`

**Comment by nareshbhatia** [comment]
FYI, this repository is fairly dated and uses Angular 1.x. If you have a hard requirement to use this version of Angular, feel free to use this template. But for all practical purposes I recommend moving on to the latest version of Angular and an appropriate template like [angular-cli](https://github.com/angular/angular-cli).
